server:
  port: 8088

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/spring_demo?allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: honganh09

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update

security:
  ignored: /**
  basic:
    enable: false
springdoc:
  swagger-ui:
    path:/swagger-ui.html
